name: deploy-cloudflare-workers
on:
  push:
    branches:
      - main
jobs:
  deploy-cloudflare-workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "workers"
